spring.application.name=orchestrix

# MySQL datasource configuration.
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Redis datasource configuration
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.username=${REDIS_USER}
spring.data.redis.ssl.enabled=true

# Keep Hibernate conservative until entities are added.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret
jwt.secret=${JWT_SECRET}

# Enable devtools restart
spring.devtools.restart.enabled=true

# Live reload (browser auto refresh)
spring.devtools.livereload.enabled=true
